import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";


export const metadata = {
    title: "HASSOUNA-SHOP-Blog",
    description: "Generated by HASSOUNA-SHOP",
  };

  
const getData = async () => {
  const response = await fetch("https://dummyjson.com/posts?skip=5&limit=10");
  return response.json();
};

const Blog = async () => {
  const data = await getData();
  const products = data.posts
  return (
    <div className={styles.mainContainer}>
      {products.map(post => (
         
          <Link href={`./blog/${post.id}`} className={styles.post} key={post.id}>
            <div className={styles.imageContainer}>
              <Image
                src={
                  "https://images.pexels.com/photos/4192443/pexels-photo-4192443.jpeg"
                }
                fill={true}
                className={styles.image}
                alt="Post Image"
              />
            </div>
            <div className={styles.content}>
              <h1 className={styles.title}>{post.title}</h1>
              <p className={styles.text}>{post.body.slice(0,150)}</p>
            </div>
          </Link>
      )
      )}
    </div>
  );
};
export default Blog;
