import Image from "next/image";
import style from "./about.module.css";
import about_image from "/public/about.svg";
import Link from "next/link";
export const metadata = {
  title: "HASSOUNA-SHOP-About",
  description: "Generated by HASSOUNA-SHOP",
};
const About = () => {
  return (
    <div >
      <div className={style.container}>
        <div className={style.imageContainer}>
          <Image fill={true} alt="About Hassouna shop" src={about_image} />
        </div>
        <div className={style.contect}>
          <h3 >About Us</h3>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries,
          </p>
         <Link className={style.button} href='/blog'>Start Now</Link>
        </div>
      </div>
    </div>
  );
};
export default About;
